name: smphr_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  internet_connection_checker_plus: ^2.5.0
  shared_preferences: ^2.3.2
  google_sign_in: ^6.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
