import 'package:app/core/theme/app_palette.dart';
import 'package:flutter/material.dart';

class AppColorScheme {
  static ColorScheme lightColorScheme = const ColorScheme(
    brightness: Brightness.light,
    primary: AppPalette.primary,
    onPrimary: AppPalette.onPrimary,
    secondary: AppPalette.secondary,
    onSecondary: AppPalette.onSecondary,
    tertiary: AppPalette.tertiary,
    onTertiary: AppPalette.onTertiary,
    primaryContainer: AppPalette.primaryContainer,
    onPrimaryContainer: AppPalette.onPrimaryContainer,
    secondaryContainer: AppPalette.secondaryContainer,
    onSecondaryContainer: AppPalette.onSecondaryContainer,
    tertiaryContainer: AppPalette.tertiaryContainer,
    onTertiaryContainer: AppPalette.onTertiaryContainer,
    error: AppPalette.error,
    onError: AppPalette.onError,
    surface: AppPalette.surface,
    onSurface: AppPalette.onSurface,
    surfaceContainer: AppPalette.surfaceContainer,
    surfaceContainerLow: AppPalette.surfaceContainerLow,
    surfaceContainerLowest: AppPalette.surfaceContainerLowest,
    surfaceContainerHigh: AppPalette.surfaceContainerHigh,
    surfaceContainerHighest: AppPalette.surfaceContainerHighest,
    outline: AppPalette.outline,
  );

  static ColorScheme darkColorScheme = const ColorScheme(
    brightness: Brightness.dark,
    primary: AppPalette.primaryDark,
    onPrimary: AppPalette.onPrimaryDark,
    secondary: AppPalette.secondaryDark,
    onSecondary: AppPalette.onSecondaryDark,
    tertiary: AppPalette.tertiaryDark,
    onTertiary: AppPalette.onTertiaryDark,
    primaryContainer: AppPalette.primaryContainerDark,
    onPrimaryContainer: AppPalette.onPrimaryContainerDark,
    secondaryContainer: AppPalette.secondaryContainerDark,
    onSecondaryContainer: AppPalette.onSecondaryContainerDark,
    tertiaryContainer: AppPalette.tertiaryContainerDark,
    onTertiaryContainer: AppPalette.onTertiaryContainerDark,
    error: AppPalette.errorDark,
    onError: AppPalette.onErrorDark,
    surface: AppPalette.surfaceDark,
    onSurface: AppPalette.onSurfaceDark,
    surfaceContainer: AppPalette.surfaceContainerDark,
    surfaceContainerLow: AppPalette.surfaceContainerLowDark,
    surfaceContainerLowest: AppPalette.surfaceContainerLowestDark,
    surfaceContainerHigh: AppPalette.surfaceContainerHighDark,
    surfaceContainerHighest: AppPalette.surfaceContainerHighestDark,
    outline: AppPalette.outlineDark,
  );
}
